#!/usr/bin/env python3
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REPLACEMENTS = {
    # English source and generated English pages.
    "daily logging": "daily dose entry",
    "Fast dose logging": "Fast dose entry",
    "provider-style PDF summaries": "clinician-ready PDF summaries",
    "Provider-style PDF summaries": "Clinician-ready PDF summaries",
    "provider-style exports": "clinician-ready exports",
    "Provider-style exports": "Clinician-ready exports",
    "provider-friendly review": "clinician-friendly review",
    "provider-friendly": "clinician-friendly",
    "Supply logging": "Supply tracking",
    "Fast logging without clutter": "Fast dose entry without clutter",
    "Fast logging": "Fast dose entry",
    "Route and cadence": "Administration route and dosing frequency",
    "Route and Cadence": "Administration route and dosing frequency",
    "Choose the packaging that matches what you use": "Choose the medicine form you use",
    "Provider Summary": "Summary for your clinician",
    "Provider summary": "Summary for your clinician",
    "Create a calm provider summary PDF": "Create a clear PDF summary for appointments",
    "Keep dose, weight, symptoms, appetite and photos in one calm place": "Keep dose, weight, symptoms, appetite and photos together in one place",
    "one calmer place": "one place",
    "Export-ready records": "CSV, JSON and PDF summaries for your records",
    "Custom / Compounded": "Custom treatment / Compounded treatment",
    "Presentations": "Medicine forms",
    "Presentation fit": "Medicine form",
    "route, presentation, cadence, or custom/compounded setup": "administration route, medicine form, dosing frequency, custom treatment, or compounded treatment setup",
    "Estimated medication level for personal tracking only. Not medical advice. Always check with your clinician before making medical decisions.": "Estimated Exposure is a personal tracking estimate, not measured blood concentration and not medical advice. Do not use Estimated Exposure to guide dosing. Always check with your clinician before making medical decisions.",
    "Estimated medication level for personal tracking only. Not medical advice.": "Estimated Exposure is a personal tracking estimate, not measured blood concentration and not medical advice.",
    "Always check with your clinician before making medical decisions.": "Do not use Estimated Exposure to guide dosing. Always check with your clinician before making medical decisions.",
    "sleep, ": "",
    "sleep, movement": "movement",
    "sleep, movement and nutrition": "movement and nutrition",
    "sleep, exercise, calories": "exercise, calories",
    "sleep, workouts, calories": "workouts, calories",
    "sleep, workout, calories": "workout, calories",
    "sleep, movement, workout": "movement, workout",
    "sleep, movement, workouts": "movement, workouts",
    "sono, movimento": "movimento",
    "sono, treino": "treino",
    "sono, movimento, treino": "movimento, treino",
    "sonno, movimento": "movimento",
    "del sonno, ": "",
    "sonno, ": "",
    "sommeil, mouvement": "mouvement",
    "du sommeil, ": "",
    "sommeil, ": "",
    "Schlaf, Bewegung": "Bewegung",
    "slaap, beweging": "beweging",
    "unen, liikkeen": "liikkeen",
    "sömn, rörelse": "rörelse",
    "睡眠、": "",
    "睡眠，": "",
    "睡眠, ": "",
    "睡眠": "",
    "수면, ": "",
    "수면": "",

    # Repeated CSV/PDF and mixed-English fragments.
    "PDF, PDF and PDF summaries": "CSV, JSON and PDF summaries",
    "PDF-, PDF- en PDF-samenvattingen": "CSV-, JSON- en PDF-samenvattingen",
    "PDF-, PDF- und PDF-Zusammenfassungen": "CSV-, JSON- und PDF-Zusammenfassungen",
    "PDF, PDF og PDF": "CSV, JSON og PDF",
    "PDF, PDF och PDF": "CSV, JSON och PDF",
    "PDF, PDF ja PDF": "CSV, JSON ja PDF",
    "PDF, PDF 및 PDF": "CSV, JSON 및 PDF",
    "PDF, PDF y PDF": "CSV, JSON y PDF",
    "PDF, PDF e PDF": "CSV, JSON e PDF",
    "PDF, PDF et PDF": "CSV, JSON et PDF",
    "Podsumowania PDF, PDF i PDF": "Podsumowania CSV, JSON i PDF",
    "Current mes stays free. Premium adds past and futura navegación.": "El mes actual sigue siendo gratis. Premium añade navegación por meses anteriores y futuros.",
    "Current maand stays free. Premium adds past and toekomst browsen.": "De huidige maand blijft gratis. Premium voegt bladeren door vorige en toekomstige maanden toe.",
    "Current mês stays free. Premium adds past and futuro navegação.": "O mês atual continua grátis. Premium adiciona navegação por meses anteriores e futuros.",
    "Unlock exports, widgets, planning tools, and deeper historia control.": "Desbloquea exportaciones, widgets, herramientas de planificación y un control más profundo del historial.",
    "Unlock exports, widgets, planning tools, and deeper geschiedenis controle.": "Ontgrendel exports, widgets, planningstools en uitgebreidere geschiedenis.",
    "Unlock exports, widgets, planning tools, and deeper histórico controle.": "Desbloqueie exportações, widgets, ferramentas de planejamento e controle mais profundo do histórico.",

    # Top/P0 locale corrections: logging, route, form, custom, clinician summaries.
    "Ātra mežizstrāde bez jucekļa": "Ātra devu reģistrēšana bez jucekļa",
    "Ātra mežizstrāde": "Ātra devu reģistrēšana",
    "Maršruts un kadence": "Ievadīšanas veids un biežums",
    "Rýchla ťažba dreva bez neporiadku": "Rýchle zaznamenávanie dávok bez neporiadku",
    "Rýchla ťažba dreva": "Rýchle zaznamenávanie dávok",
    "Trasa a kadencia": "Spôsob podania a frekvencia",
    "Rychlá těžba dřeva bez nepořádku": "Rychlé zaznamenávání dávek bez nepořádku",
    "Rychlá těžba dřeva": "Rychlé zaznamenávání dávek",
    "Trasa a kadence": "Způsob podání a frekvence",
    "Kiire metsaraie ilma segaduseta": "Kiire annuste märkimine ilma segaduseta",
    "Kiire metsaraie": "Kiire annuste märkimine",
    "Marsruut ja kadents": "Manustamisviis ja sagedus",
    "Seotud": "Apteegis valmistatud",
    "เข้าสู่ระบบอย่างรวดเร็วโดยไม่เกะกะ": "บันทึกยาได้รวดเร็ว ไม่รก",
    "เข้าสู่ระบบอย่างรวดเร็ว": "บันทึกยาได้รวดเร็ว",
    "แนวโน้มความเสี่ยงที่คาดการณ์ไว้": "แนวโน้มการได้รับยาโดยประมาณ",
    "ความเป็นส่วนตัว policy": "นโยบายความเป็นส่วนตัว",
    "เลือก ของคุณ medication": "เลือกยาของคุณ",
    "คำสั่งซื้อ": "การเตือน",
    "Đăng nhập nhanh chóng mà không lộn xộn": "Ghi liều nhanh, gọn gàng",
    "Đăng nhập nhanh chóng": "Ghi liều nhanh",
    "Quyền riêng tư policy": "Chính sách quyền riêng tư",
    "Chọn của bạn medication": "Chọn thuốc của bạn",
    "路线和节奏": "给药方式和用药频率",
    "路線和節奏": "給藥方式與用藥頻率",
    "选择与您使用的产品相匹配的包装": "选择与你使用的药品相符的剂型或给药形式",
    "選擇與您使用的產品相符的包裝": "選擇與你使用的藥品相符的劑型或給藥形式",
    "提供商摘要": "给医生的摘要",
    "提供者摘要": "給醫師的摘要",
    "安静的地方": "集中保存在一处",
    "安靜的地方": "集中保存在一處",
    "订单": "提醒",
    "訂單": "提醒",
    "Itinéraire et cadence": "Voie d’administration et fréquence",
    "Choisissez l’emballage qui correspond au produit que vous utilisez": "Choisissez la forme qui correspond à votre traitement",
    "Résumé du fournisseur": "Résumé pour le professionnel de santé",
    "résumé du fournisseur": "résumé pour le professionnel de santé",
    "résumé calme du fournisseur": "résumé clair pour le professionnel de santé",
    "Coutume": "Personnalisé",
    "endroit calme": "même endroit",
    "Route und Kadenz": "Anwendungsweg und Häufigkeit",
    "Wählen Sie die Verpackung, die dem von Ihnen verwendeten Produkt entspricht": "Wählen Sie die Darreichungsform, die zu Ihrem Präparat passt",
    "Anbieterübersicht": "Zusammenfassung für Behandelnde",
    "ルートとリズム": "投与経路と頻度",
    "プロバイダーの概要": "医療者向けサマリー",
    "静かな場所": "1か所にまとめて保存",
    "注文": "リマインダー",
    "경로 및 케이던스": "투여 경로 및 주기",
    "공급자 요약": "의료진용 요약",
    "제공자 요약": "의료진용 요약",
    "차분한 곳": "한곳에 정리해 보관",
    "Route en cadans": "Toedieningsweg en frequentie",
    "Samenvatting van de leverancier": "Samenvatting voor je zorgverlener",
    "Ruta y cadencia": "Vía de administración y frecuencia",
    "Elige el embalaje que coincida con el producto que usas": "Elige la presentación que corresponde al medicamento que usas",
    "Resumen del proveedor": "Resumen para tu profesional sanitario",
    "Rota e cadência": "Via de administração e frequência",
    "Percorso e cadenza": "Via di somministrazione e frequenza",
    "Trasa i rytm": "Droga podania i częstotliwość dawkowania",
    "मार्ग और ताल": "प्रशासन का तरीका और खुराक की आवृत्ति",
    "Resumo do provedor": "Resumo para seu profissional de saúde",
    "resumo tranquilo do provedor": "resumo claro para seu profissional de saúde",
    "Escolha a embalagem que corresponda ao produto que utiliza": "Escolha a forma que corresponde ao medicamento que utiliza",
    "Escolha a embalagem que corresponda ao produto que você usa": "Escolha a forma que corresponde ao medicamento que você usa",
    "pedidos": "lembretes",
    "الطلبات": "التذكيرات",
    "المسار والإيقاع": "طريقة الإعطاء وتكرار الجرعة",
    "ملخص الموفر": "ملخص للطبيب",
    "مكان واحد هادئ": "مكان واحد واضح ومنظّم",
    "Costume": "Personalizzato",
    "Costumbre": "Personalizado",
    "Skik": "Tilpasset",
    "Маршрут и частота вращения педалей": "Способ применения и частота",
    "Rute dan irama": "Rute pemberian dan frekuensi",
    "Trasa i rytm": "Droga podania i częstotliwość dawkowania",
    "See App Store pricing\u200b": "See App Store pricing",
    "provider-style PDFs": "clinician-ready PDFs",
    "provider-style PDF": "clinician-ready PDF",
    "Estimated Exposure Trend is a relative personal-tracking estimate derived from the dose timing the user logs, the selected medicine context, and a parameterised absorption-and-elimination model. It is intended to help users review timing patterns in their own records, not to provide clinical measurement.": "Estimated Exposure is a personal tracking estimate, not measured blood concentration. Estimated Exposure Trend is derived from the dose timing the user logs, the selected medicine context, and a parameterised absorption-and-elimination model. It is intended to help users review timing patterns in their own records, not to provide clinical measurement or dosing guidance.",
    "GLPzy is a tracking and journaling service. It does not provide medical advice and must not be used to make medical or dosing decisions.": "Estimated Exposure is a personal tracking estimate, not measured blood concentration and not medical advice. Do not use Estimated Exposure to guide dosing. GLPzy is a tracking and journaling service and must not be used to make medical or dosing decisions.",
    "Do not use Estimated Exposure to guide dosing. Do not use Estimated Exposure to guide dosing. Do not use Estimated Exposure to guide dosing. Do not use Estimated Exposure to guide dosing.": "Do not use Estimated Exposure to guide dosing.",
    "Do not use Estimated Exposure to guide dosing. Do not use Estimated Exposure to guide dosing. Do not use Estimated Exposure to guide dosing.": "Do not use Estimated Exposure to guide dosing.",
    "Do not use Estimated Exposure to guide dosing. Do not use Estimated Exposure to guide dosing.": "Do not use Estimated Exposure to guide dosing.",
    "setup, logging, reminders": "setup, daily dose entry, reminders",
    "Keep dose, weight, symptoms, appetite and photos in one calm place.": "Keep dose, weight, symptoms, appetite and photos together in one place.",
    "Create a calm provider summary PDF from your logged treatment, weight, symptoms and measurements.": "Create a clear PDF summary for appointments from your logged treatment, weight, symptoms and measurements.",
    "No account is required to track doses, weight, symptoms, reminders or orders.": "No in-app account is required to record doses, weight, symptoms or reminders.",
    "No account required to track doses, weight, symptoms, reminders or orders.": "No in-app account is required to record doses, weight, symptoms or reminders.",
    "No account required to track doses, weight, symptoms or reminders.": "No in-app account is required to record doses, weight, symptoms or reminders.",
    "No account required to record doses, weight, symptoms or reminders": "No in-app account is required to record doses, weight, symptoms or reminders",
    "Export-ready records: CSV, JSON and PDF": "CSV, JSON and PDF summaries for your records",

    # PT-PT generated-page corruption from the previous bulk rewrite.
    "hero-via a a sual": "hero-visual",

    # Remaining Phase 2 generated locale cleanup.
    "गोंधळाशिवाय द्रुत लॉगिंग": "गोंधळाशिवाय द्रुत डोस नोंद",
    "मार्ग आणि ताल": "देण्याचा मार्ग आणि डोस वारंवारता",
    "तुम्ही वापरत असलेल्या पॅकेजिंगशी जुळणारे पॅकेजिंग निवडा. तुम्ही हे नंतर बदलू शकता.": "तुम्ही वापरत असलेला औषधाचा प्रकार निवडा. तुम्ही हे नंतर बदलू शकता.",
    "सादरीकरण निवडी बंडल केलेल्या देशाच्या नियमांचे पालन करतात.": "औषधाच्या प्रकारांच्या निवडी बंडल केलेल्या देशाच्या नियमांचे पालन करतात.",
    "सादरीकरणे": "औषधाचे प्रकार",
    "सादरीकरण": "औषधाचा प्रकार",
    "एकाच शांत ठिकाणी": "एकाच ठिकाणी",
    "प्रदाता सारांश": "तुमच्या चिकित्सकासाठी सारांश",
    "तुमच्या लॉग इन केलेले उपचार, वजन, लक्षणे आणि मोजमापांमधून शांत प्रदाता सारांश PDF तयार करा.": "तुमच्या नोंदवलेल्या उपचार, वजन, लक्षणे आणि मोजमापांमधून भेटीसाठी स्पष्ट PDF सारांश तयार करा.",
    "Non è richiesto alcun account per tenere traccia di dosi, peso, sintomi, promemoria o ordini.": "Non serve un account nell’app per registrare dosi, peso, sintomi o promemoria.",
    "Tiliä ei tarvita annosten, painon, oireiden, muistutusten tai tilausten seuraamiseen.": "Tiliä ei tarvita annosten, painon, oireiden tai muistutusten kirjaamiseen.",
    "Palveluntarjoajan yhteenveto": "Yhteenveto lääkärille",
    "Luo rauhallinen palveluntarjoajan yhteenveto PDF kirjautuneesta hoidostasi, painostasi, oireistasi ja mittauksistasi.": "Luo selkeä PDF-yhteenveto vastaanottoja varten kirjatusta hoidosta, painosta, oireista ja mittauksista.",
    "rauhallisessa paikassa": "yhdessä paikassa",
    "Der kræves ingen konto for at spore doser, vægt, symptomer, påmindelser eller ordrer.": "Der kræves ingen konto i appen for at registrere doser, vægt, symptomer eller påmindelser.",
    "Apple Health adgang er valgfri og begrænset til de tilladelser, du giver. GLPzy importerer kropsvægthistorie og højde og læser derefter kropssammensætning, søvn, bevægelse, træning, kalorier, protein og vand i skrivebeskyttet tilstand. Intet er skrevet tilbage.": "Apple Health adgang er valgfri og begrænset til de tilladelser, du giver. GLPzy importerer kropsvægthistorie og højde og læser derefter kropssammensætning, bevægelse, træning, kalorier, protein og vand i skrivebeskyttet tilstand. Intet er skrevet tilbage.",
    "søvn, bevægelse": "bevægelse",
    "Tiada akaun diperlukan untuk menjejaki dos, berat, gejala, peringatan atau pesanan.": "Tiada akaun dalam app diperlukan untuk merekod dos, berat, gejala atau peringatan.",
    "Akses Apple Health adalah pilihan dan terhad kepada kebenaran yang anda berikan. GLPzy mengimport sejarah berat badan dan ketinggian, kemudian membaca komposisi badan, tidur, pergerakan, senaman, kalori, protein dan ringkasan air dalam mod baca sahaja. Tiada apa yang ditulis kembali.": "Akses Apple Health adalah pilihan dan terhad kepada kebenaran yang anda berikan. GLPzy mengimport sejarah berat badan dan ketinggian, kemudian membaca komposisi badan, pergerakan, senaman, kalori, protein dan ringkasan air dalam mod baca sahaja. Tiada apa yang ditulis kembali.",
    "tidur, pergerakan": "pergerakan",
    "Tidak diperlukan akun untuk melacak dosis, berat badan, gejala, pengingat, atau pesanan.": "Tidak diperlukan akun dalam app untuk mencatat dosis, berat badan, gejala, atau pengingat.",
    "Akses Apple Health bersifat opsional dan terbatas pada izin yang Anda berikan. GLPzy mengimpor riwayat berat badan dan tinggi badan, lalu membaca ringkasan komposisi tubuh, tidur, gerakan, olahraga, kalori, protein, dan air dalam mode hanya baca. Tidak ada yang ditulis kembali.": "Akses Apple Health bersifat opsional dan terbatas pada izin yang Anda berikan. GLPzy mengimpor riwayat berat badan dan tinggi badan, lalu membaca ringkasan komposisi tubuh, gerakan, olahraga, kalori, protein, dan air dalam mode hanya baca. Tidak ada yang ditulis kembali.",
    "Apple Health-tilgang er valgfri og begrenset til tillatelsene du gir. GLPzy importerer kroppsvekthistorikk og høyde, og leser deretter sammensetninger av kroppssammensetning, søvn, bevegelse, trening, kalorier, proteiner og vann i skrivebeskyttet modus. Ingenting er skrevet tilbake.": "Apple Health-tilgang er valgfri og begrenset til tillatelsene du gir. GLPzy importerer kroppsvekthistorikk og høyde, og leser deretter kroppssammensetning, bevegelse, trening, kalorier, proteiner og vann i skrivebeskyttet modus. Ingenting er skrevet tilbake.",
}

INDEX_BLOCK_REPLACEMENTS = {
    "da": {
        "site.premium.body": "Lås eksport, widgets, planlægningsværktøjer og dybere historik op.",
        "site.card.premium.calendar.body": "Den aktuelle måned er gratis. Premium tilføjer browsing i tidligere og fremtidige måneder.",
        "site.card.premium.exports.body": "CSV-, JSON- og PDF-oversigter til dine egne optegnelser",
    },
    "fi": {
        "site.premium.body": "Avaa viennit, widgetit, suunnittelutyökalut ja laajempi historian tarkistus.",
        "site.card.premium.calendar.body": "Nykyinen kuukausi pysyy maksuttomana. Premium lisää aiempien ja tulevien kuukausien selaamisen.",
        "site.card.premium.exports.body": "CSV-, JSON- ja PDF-yhteenvedot omia tietoja varten",
    },
    "es-es": {
        "site.premium.body": "Desbloquea exportaciones, widgets, herramientas de planificación y una revisión más profunda del historial.",
        "site.card.premium.calendar.body": "El mes actual sigue siendo gratis. Premium añade navegación por meses anteriores y futuros.",
        "site.card.premium.exports.body": "Resúmenes en CSV, JSON y PDF para tus propios registros",
    },
    "es-mx": {
        "site.premium.body": "Desbloquea exportaciones, widgets, herramientas de planificación y una revisión más profunda del historial.",
        "site.card.premium.calendar.body": "El mes actual sigue siendo gratis. Premium agrega navegación por meses anteriores y futuros.",
        "site.card.premium.exports.body": "Resúmenes en CSV, JSON y PDF para tus propios registros",
    },
    "it": {
        "site.premium.body": "Sblocca esportazioni, widget, strumenti di pianificazione e un controllo più approfondito della cronologia.",
        "site.card.premium.calendar.body": "Il mese corrente resta gratuito. Premium aggiunge la consultazione dei mesi precedenti e futuri.",
        "site.card.premium.exports.body": "Riepiloghi CSV, JSON e PDF per i tuoi archivi",
    },
    "ja": {
        "site.premium.body": "エクスポート、ウィジェット、計画ツール、より詳しい履歴確認を利用できます。",
        "site.card.premium.calendar.body": "現在の月は無料です。Premium では過去と今後の月を閲覧できます。",
        "site.card.premium.exports.body": "自分の記録用の CSV、JSON、PDF サマリー",
    },
    "ko": {
        "site.premium.body": "내보내기, 위젯, 계획 도구와 더 자세한 기록 확인을 이용할 수 있습니다.",
        "site.card.premium.calendar.body": "현재 월은 무료입니다. Premium에서는 이전 및 이후 월을 볼 수 있습니다.",
        "site.card.premium.exports.body": "개인 기록용 CSV, JSON 및 PDF 요약",
    },
    "nb": {
        "site.premium.body": "Lås opp eksport, widgeter, planleggingsverktøy og dypere historikk.",
        "site.card.premium.calendar.body": "Gjeldende måned er gratis. Premium legger til visning av tidligere og fremtidige måneder.",
        "site.card.premium.exports.body": "CSV-, JSON- og PDF-sammendrag for egne opptegnelser",
    },
    "nl": {
        "site.premium.body": "Ontgrendel exports, widgets, planningstools en uitgebreidere geschiedenis.",
        "site.card.premium.calendar.body": "De huidige maand blijft gratis. Premium voegt bladeren door vorige en toekomstige maanden toe.",
        "site.card.premium.exports.body": "CSV-, JSON- en PDF-samenvattingen voor uw eigen administratie",
    },
    "pl": {
        "site.premium.body": "Odblokuj eksporty, widżety, narzędzia planowania i dokładniejszy przegląd historii.",
        "site.card.premium.calendar.body": "Bieżący miesiąc pozostaje bezpłatny. Premium dodaje przegląd poprzednich i przyszłych miesięcy.",
        "site.card.premium.exports.body": "Podsumowania CSV, JSON i PDF do własnej dokumentacji",
    },
    "pt-br": {
        "site.premium.body": "Desbloqueie exportações, widgets, ferramentas de planejamento e revisão mais profunda do histórico.",
        "site.card.premium.calendar.body": "O mês atual continua grátis. Premium adiciona navegação por meses anteriores e futuros.",
        "site.card.premium.exports.body": "Resumos em CSV, JSON e PDF para seus próprios registros",
    },
    "pt-pt": {
        "site.premium.body": "Desbloqueie exportações, widgets, ferramentas de planeamento e revisão mais profunda do histórico.",
        "site.card.premium.calendar.body": "O mês atual continua grátis. Premium adiciona navegação por meses anteriores e futuros.",
        "site.card.premium.exports.body": "Resumos em CSV, JSON e PDF para os seus próprios registos",
    },
    "ru": {
        "onboarding.medication.routeCadence": "Способ применения и частота",
        "onboarding.medication.presentation.detail": "Выберите форму препарата, которую вы используете. Вы можете изменить это позже.",
        "settings.copy.presentation": "Форма препарата",
        "site.card.provider.title": "Сводка для врача",
        "site.product.card.summary.title": "Сводка для врача",
        "site.card.provider.body": "Создайте понятную PDF-сводку для приёма на основе записанного лечения, веса, симптомов и измерений.",
        "site.product.card.summary.body": "Создайте понятную PDF-сводку для приёма на основе записанного лечения, веса, симптомов и измерений.",
        "site.card.log.body": "Храните дозу, вес, симптомы, аппетит и фотографии вместе в одном месте.",
        "site.product.card.log.body": "Храните дозу, вес, симптомы, аппетит и фотографии вместе в одном месте.",
    },
    "mr": {
        "onboarding.medication.routeCadence": "देण्याचा मार्ग आणि डोस वारंवारता",
        "onboarding.medication.presentation.detail": "तुम्ही वापरत असलेला औषधाचा प्रकार निवडा. तुम्ही हे नंतर बदलू शकता.",
        "settings.copy.presentation": "औषधाचा प्रकार",
        "site.card.provider.title": "तुमच्या चिकित्सकासाठी सारांश",
        "site.product.card.summary.title": "तुमच्या चिकित्सकासाठी सारांश",
        "site.card.provider.body": "तुमच्या नोंदवलेल्या उपचार, वजन, लक्षणे आणि मोजमापांमधून भेटीसाठी स्पष्ट PDF सारांश तयार करा.",
        "site.product.card.summary.body": "तुमच्या नोंदवलेल्या उपचार, वजन, लक्षणे आणि मोजमापांमधून भेटीसाठी स्पष्ट PDF सारांश तयार करा.",
        "site.card.log.body": "डोस, वजन, लक्षणे, भूक आणि फोटो एकाच ठिकाणी ठेवा.",
        "site.product.card.log.body": "डोस, वजन, लक्षणे, भूक आणि फोटो एकाच ठिकाणी ठेवा.",
    },
    "sv": {
        "site.premium.body": "Lås upp export, widgetar, planeringsverktyg och djupare historik.",
        "site.card.premium.calendar.body": "Den aktuella månaden är gratis. Premium lägger till bläddring i tidigare och kommande månader.",
        "site.card.premium.exports.body": "CSV-, JSON- och PDF-sammanfattningar för dina egna anteckningar",
    },
    "th": {
        "site.premium.body": "ปลดล็อกการส่งออก วิดเจ็ต เครื่องมือวางแผน และการตรวจสอบประวัติที่ละเอียดขึ้น",
        "site.card.premium.calendar.body": "เดือนปัจจุบันยังใช้ฟรี Premium เพิ่มการดูเดือนก่อนหน้าและเดือนถัดไป",
        "site.card.premium.exports.body": "สรุป CSV, JSON และ PDF สำหรับบันทึกของคุณ",
    },
    "vi": {
        "site.premium.body": "Mở khóa xuất dữ liệu, widget, công cụ lập kế hoạch và xem lại lịch sử sâu hơn.",
        "site.card.premium.calendar.body": "Tháng hiện tại vẫn miễn phí. Premium thêm khả năng xem các tháng trước và sau.",
        "site.card.premium.exports.body": "Tóm tắt CSV, JSON và PDF cho hồ sơ cá nhân của bạn",
    },
}

DEFAULT_BLOCK_REPLACEMENTS = {
    "onboarding.medication.routeCadence": "Administration route and dosing frequency",
    "onboarding.medication.presentation.detail": "Choose the medicine form you use. You can change this later.",
    "settings.copy.presentation": "Medicine form",
    "site.card.provider.title": "Summary for your clinician",
    "site.product.card.summary.title": "Summary for your clinician",
    "site.card.provider.body": "Create a clear PDF summary for appointments from your logged treatment, weight, symptoms and measurements.",
    "site.product.card.summary.body": "Create a clear PDF summary for appointments from your logged treatment, weight, symptoms and measurements.",
    "site.card.log.title": "Fast dose entry without clutter.",
    "site.product.card.log.title": "Fast dose entry without clutter.",
    "site.card.log.body": "Keep dose, weight, symptoms, appetite and photos together in one place.",
    "site.product.card.log.body": "Keep dose, weight, symptoms, appetite and photos together in one place.",
    "site.privacy.detail.body": "No in-app account is required to record doses, weight, symptoms or reminders.",
    "site.privacy.body": "No in-app account is required to record doses, weight, symptoms or reminders.",
    "site.card.account.title": "No in-app account is required to record doses, weight, symptoms or reminders.",
    "services.copy.no.account.is.required.to.track.doses.weight": "No in-app account is required to record doses, weight, symptoms or reminders.",
    "site.health.detail.body": "Apple Health access is optional and limited to the permissions you grant. GLPzy imports body weight history and height, then reads body composition, movement, workout, calorie, protein and water summaries in read-only mode. Nothing is written back.",
    "site.card.health.body": "Apple Health access is optional and limited to the permissions you grant. GLPzy imports body weight history and height, then reads body composition, movement, workout, calorie, protein and water summaries in read-only mode. Nothing is written back.",
    "services.copy.apple.health.access.is.optional.and.limited.to": "Apple Health access is optional and limited to the permissions you grant. GLPzy imports body weight history and height, then reads body composition, movement, workout, calorie, protein and water summaries in read-only mode. Nothing is written back.",
}

LOCALE_BLOCK_REPLACEMENTS = {
    "en": {
        "onboarding.medication.routeCadence": "Administration route and dosing frequency",
        "onboarding.medication.presentation.detail": "Choose the medicine form you use. You can change this later.",
        "settings.copy.presentation": "Medicine form",
        "site.card.provider.title": "Summary for your clinician",
        "site.product.card.summary.title": "Summary for your clinician",
        "site.card.provider.body": "Create a clear PDF summary for appointments from your logged treatment, weight, symptoms and measurements.",
        "site.product.card.summary.body": "Create a clear PDF summary for appointments from your logged treatment, weight, symptoms and measurements.",
        "site.card.log.title": "Fast dose entry without clutter.",
        "site.product.card.log.title": "Fast dose entry without clutter.",
        "site.card.log.body": "Keep dose, weight, symptoms, appetite and photos together in one place.",
        "site.product.card.log.body": "Keep dose, weight, symptoms, appetite and photos together in one place.",
        "site.privacy.detail.body": "No in-app account is required to record doses, weight, symptoms or reminders.",
        "site.card.account.title": "No in-app account is required to record doses, weight, symptoms or reminders.",
    },
    "en-gb": {
        "onboarding.medication.routeCadence": "Administration route and dosing frequency",
        "onboarding.medication.presentation.detail": "Choose the medicine form you use. You can change this later.",
        "settings.copy.presentation": "Medicine form",
        "site.card.provider.title": "Summary for your clinician",
        "site.product.card.summary.title": "Summary for your clinician",
        "site.card.provider.body": "Create a clear PDF summary for appointments from your logged treatment, weight, symptoms and measurements.",
        "site.product.card.summary.body": "Create a clear PDF summary for appointments from your logged treatment, weight, symptoms and measurements.",
        "site.card.log.title": "Fast dose entry without clutter.",
        "site.product.card.log.title": "Fast dose entry without clutter.",
        "site.card.log.body": "Keep dose, weight, symptoms, appetite and photos together in one place.",
        "site.product.card.log.body": "Keep dose, weight, symptoms, appetite and photos together in one place.",
        "site.privacy.detail.body": "No in-app account is required to record doses, weight, symptoms or reminders.",
        "site.card.account.title": "No in-app account is required to record doses, weight, symptoms or reminders.",
    },
    "de": {
        "onboarding.medication.routeCadence": "Anwendungsweg und Häufigkeit",
        "onboarding.medication.presentation.detail": "Wählen Sie die Darreichungsform, die zu Ihrem Präparat passt. Sie können dies später ändern.",
        "settings.copy.presentation": "Darreichungsform",
        "site.card.provider.title": "Zusammenfassung für Behandelnde",
        "site.product.card.summary.title": "Zusammenfassung für Behandelnde",
        "site.card.provider.body": "Erstellen Sie eine klare PDF-Zusammenfassung für Termine aus Ihrer erfassten Behandlung, Ihrem Gewicht, Ihren Symptomen und Messwerten.",
        "site.product.card.summary.body": "Erstellen Sie eine klare PDF-Zusammenfassung für Termine aus Ihrer erfassten Behandlung, Ihrem Gewicht, Ihren Symptomen und Messwerten.",
        "site.card.log.body": "Bewahren Sie Dosis, Gewicht, Symptome, Appetit und Fotos gemeinsam an einem Ort auf.",
        "site.product.card.log.body": "Bewahren Sie Dosis, Gewicht, Symptome, Appetit und Fotos gemeinsam an einem Ort auf.",
        "site.privacy.detail.body": "Kein In-App-Konto ist erforderlich, um Dosen, Gewicht, Symptome oder Erinnerungen zu erfassen.",
        "site.card.account.title": "Kein In-App-Konto ist erforderlich, um Dosen, Gewicht, Symptome oder Erinnerungen zu erfassen.",
    },
    "es-es": {
        "onboarding.medication.routeCadence": "Vía de administración y frecuencia",
        "onboarding.medication.presentation.detail": "Elige la presentación que corresponde al medicamento que usas. Puedes cambiarlo más tarde.",
        "settings.copy.presentation": "Presentación",
        "site.card.provider.title": "Resumen para tu profesional sanitario",
        "site.product.card.summary.title": "Resumen para tu profesional sanitario",
        "site.card.provider.body": "Crea un resumen PDF claro para tus citas a partir del tratamiento, peso, síntomas y mediciones registrados.",
        "site.product.card.summary.body": "Crea un resumen PDF claro para tus citas a partir del tratamiento, peso, síntomas y mediciones registrados.",
        "site.card.log.body": "Mantén dosis, peso, síntomas, apetito y fotos juntos en un solo lugar.",
        "site.product.card.log.body": "Mantén dosis, peso, síntomas, apetito y fotos juntos en un solo lugar.",
        "site.privacy.detail.body": "No se requiere una cuenta en la app para registrar dosis, peso, síntomas o recordatorios.",
        "site.card.account.title": "No se requiere una cuenta en la app para registrar dosis, peso, síntomas o recordatorios.",
    },
    "es-mx": {
        "onboarding.medication.routeCadence": "Vía de administración y frecuencia",
        "onboarding.medication.presentation.detail": "Elige la presentación que corresponde al medicamento que usas. Puedes cambiarlo más tarde.",
        "settings.copy.presentation": "Presentación",
        "site.card.provider.title": "Resumen para tu profesional sanitario",
        "site.product.card.summary.title": "Resumen para tu profesional sanitario",
        "site.card.provider.body": "Crea un resumen PDF claro para tus citas a partir del tratamiento, peso, síntomas y mediciones registrados.",
        "site.product.card.summary.body": "Crea un resumen PDF claro para tus citas a partir del tratamiento, peso, síntomas y mediciones registrados.",
        "site.card.log.body": "Mantén dosis, peso, síntomas, apetito y fotos juntos en un solo lugar.",
        "site.product.card.log.body": "Mantén dosis, peso, síntomas, apetito y fotos juntos en un solo lugar.",
        "site.privacy.detail.body": "No se requiere una cuenta en la app para registrar dosis, peso, síntomas o recordatorios.",
        "site.card.account.title": "No se requiere una cuenta en la app para registrar dosis, peso, síntomas o recordatorios.",
    },
    "fr": {
        "onboarding.medication.routeCadence": "Voie d’administration et fréquence",
        "onboarding.medication.presentation.detail": "Choisissez la forme qui correspond à votre traitement. Vous pourrez la modifier plus tard.",
        "settings.copy.presentation": "Forme",
        "site.card.provider.title": "Résumé pour le professionnel de santé",
        "site.product.card.summary.title": "Résumé pour le professionnel de santé",
        "site.card.provider.body": "Créez un résumé PDF clair pour les rendez-vous à partir du traitement, du poids, des symptômes et des mesures enregistrés.",
        "site.product.card.summary.body": "Créez un résumé PDF clair pour les rendez-vous à partir du traitement, du poids, des symptômes et des mesures enregistrés.",
        "site.card.log.body": "Gardez dose, poids, symptômes, appétit et photos ensemble au même endroit.",
        "site.product.card.log.body": "Gardez dose, poids, symptômes, appétit et photos ensemble au même endroit.",
        "site.privacy.detail.body": "Aucun compte dans l’app n’est requis pour enregistrer les doses, le poids, les symptômes ou les rappels.",
        "site.card.account.title": "Aucun compte dans l’app n’est requis pour enregistrer les doses, le poids, les symptômes ou les rappels.",
    },
    "fr-ca": {
        "onboarding.medication.routeCadence": "Voie d’administration et fréquence",
        "onboarding.medication.presentation.detail": "Choisissez la forme qui correspond à votre traitement. Vous pourrez la modifier plus tard.",
        "settings.copy.presentation": "Forme",
        "site.card.provider.title": "Résumé pour le professionnel de santé",
        "site.product.card.summary.title": "Résumé pour le professionnel de santé",
        "site.card.provider.body": "Créez un résumé PDF clair pour les rendez-vous à partir du traitement, du poids, des symptômes et des mesures enregistrés.",
        "site.product.card.summary.body": "Créez un résumé PDF clair pour les rendez-vous à partir du traitement, du poids, des symptômes et des mesures enregistrés.",
        "site.card.log.body": "Gardez dose, poids, symptômes, appétit et photos ensemble au même endroit.",
        "site.product.card.log.body": "Gardez dose, poids, symptômes, appétit et photos ensemble au même endroit.",
        "site.privacy.detail.body": "Aucun compte dans l’app n’est requis pour enregistrer les doses, le poids, les symptômes ou les rappels.",
        "site.card.account.title": "Aucun compte dans l’app n’est requis pour enregistrer les doses, le poids, les symptômes ou les rappels.",
    },
    "it": {
        "onboarding.medication.routeCadence": "Via di somministrazione e frequenza",
        "onboarding.medication.presentation.detail": "Scegli la forma del farmaco che usi. Puoi modificarla in seguito.",
        "settings.copy.presentation": "Forma del farmaco",
        "site.card.provider.title": "Riepilogo per il medico",
        "site.product.card.summary.title": "Riepilogo per il medico",
        "site.card.provider.body": "Crea un riepilogo PDF chiaro per gli appuntamenti dal trattamento, peso, sintomi e misurazioni registrati.",
        "site.product.card.summary.body": "Crea un riepilogo PDF chiaro per gli appuntamenti dal trattamento, peso, sintomi e misurazioni registrati.",
        "site.card.log.body": "Tieni dose, peso, sintomi, appetito e foto insieme in un unico posto.",
        "site.product.card.log.body": "Tieni dose, peso, sintomi, appetito e foto insieme in un unico posto.",
        "site.privacy.detail.body": "Non serve un account nell’app per registrare dosi, peso, sintomi o promemoria.",
        "site.card.account.title": "Non serve un account nell’app per registrare dosi, peso, sintomi o promemoria.",
    },
    "nl": {
        "onboarding.medication.routeCadence": "Toedieningsweg en frequentie",
        "onboarding.medication.presentation.detail": "Kies de toedieningsvorm die past bij wat u gebruikt. U kunt dit later wijzigen.",
        "settings.copy.presentation": "Toedieningsvorm",
        "settings.tile.support.title": "Ondersteuning",
        "site.card.provider.title": "Samenvatting voor je zorgverlener",
        "site.product.card.summary.title": "Samenvatting voor je zorgverlener",
        "site.card.provider.body": "Maak een duidelijke PDF-samenvatting voor afspraken op basis van uw geregistreerde behandeling, gewicht, symptomen en metingen.",
        "site.product.card.summary.body": "Maak een duidelijke PDF-samenvatting voor afspraken op basis van uw geregistreerde behandeling, gewicht, symptomen en metingen.",
        "site.card.log.body": "Bewaar dosis, gewicht, symptomen, eetlust en foto's samen op één plek.",
        "site.product.card.log.body": "Bewaar dosis, gewicht, symptomen, eetlust en foto's samen op één plek.",
        "site.privacy.detail.body": "Er is geen account in de app vereist om doses, gewicht, symptomen of herinneringen vast te leggen.",
        "site.card.account.title": "Er is geen account in de app vereist om doses, gewicht, symptomen of herinneringen vast te leggen.",
    },
    "pl": {
        "onboarding.medication.routeCadence": "Droga podania i częstotliwość dawkowania",
        "onboarding.medication.presentation.detail": "Wybierz formę leku, której używasz. Możesz to zmienić później.",
        "settings.copy.presentation": "Forma leku",
        "site.card.provider.title": "Podsumowanie dla lekarza",
        "site.product.card.summary.title": "Podsumowanie dla lekarza",
        "site.card.provider.body": "Utwórz jasne podsumowanie PDF na wizytę z zarejestrowanego leczenia, masy ciała, objawów i pomiarów.",
        "site.product.card.summary.body": "Utwórz jasne podsumowanie PDF na wizytę z zarejestrowanego leczenia, masy ciała, objawów i pomiarów.",
        "site.card.log.body": "Trzymaj dawkę, wagę, objawy, apetyt i zdjęcia razem w jednym miejscu.",
        "site.product.card.log.body": "Trzymaj dawkę, wagę, objawy, apetyt i zdjęcia razem w jednym miejscu.",
        "site.privacy.detail.body": "Konto w aplikacji nie jest wymagane do zapisywania dawek, wagi, objawów ani przypomnień.",
        "site.card.account.title": "Konto w aplikacji nie jest wymagane do zapisywania dawek, wagi, objawów ani przypomnień.",
    },
    "pt-br": {
        "onboarding.medication.routeCadence": "Via de administração e frequência",
        "onboarding.medication.presentation.detail": "Escolha a forma que corresponde ao medicamento que você usa. Você pode alterar isso mais tarde.",
        "settings.copy.presentation": "Forma do medicamento",
        "site.card.provider.title": "Resumo para seu profissional de saúde",
        "site.product.card.summary.title": "Resumo para seu profissional de saúde",
        "site.card.provider.body": "Crie um resumo em PDF claro para consultas a partir do tratamento, peso, sintomas e medidas registrados.",
        "site.product.card.summary.body": "Crie um resumo em PDF claro para consultas a partir do tratamento, peso, sintomas e medidas registrados.",
        "site.card.log.body": "Mantenha dose, peso, sintomas, apetite e fotos juntos em um só lugar.",
        "site.product.card.log.body": "Mantenha dose, peso, sintomas, apetite e fotos juntos em um só lugar.",
        "site.privacy.detail.body": "Nenhuma conta no app é necessária para registrar doses, peso, sintomas ou lembretes.",
        "site.card.account.title": "Nenhuma conta no app é necessária para registrar doses, peso, sintomas ou lembretes.",
    },
    "pt-pt": {
        "onboarding.medication.routeCadence": "Via de administração e frequência",
        "onboarding.medication.presentation.detail": "Escolha a forma que corresponde ao medicamento que utiliza. Pode alterar isto mais tarde.",
        "settings.copy.presentation": "Forma do medicamento",
        "site.card.provider.title": "Resumo para o seu profissional de saúde",
        "site.product.card.summary.title": "Resumo para o seu profissional de saúde",
        "site.card.provider.body": "Crie um resumo em PDF claro para consultas a partir do tratamento, peso, sintomas e medições registados.",
        "site.product.card.summary.body": "Crie um resumo em PDF claro para consultas a partir do tratamento, peso, sintomas e medições registados.",
        "site.card.log.title": "Registo rápido e sem confusão.",
        "site.product.card.log.title": "Registo rápido e sem confusão.",
        "site.card.log.body": "Mantenha dose, peso, sintomas, apetite e fotografias juntos num só local.",
        "site.product.card.log.body": "Mantenha dose, peso, sintomas, apetite e fotografias juntos num só local.",
        "site.privacy.detail.body": "Não é necessária uma conta na app para registar doses, peso, sintomas ou lembretes.",
        "site.card.account.title": "Não é necessária uma conta na app para registar doses, peso, sintomas ou lembretes.",
        "site.privacy.body": "Não é necessária uma conta na app para registar doses, peso, sintomas ou lembretes.",
        "services.copy.no.account.is.required.to.track.doses.weight": "Não é necessária uma conta na app para registar doses, peso, sintomas ou lembretes.",
        "site.card.health.body": "O acesso ao Apple Health é opcional e limitado às permissões que concede. O GLPzy importa o histórico de peso e a altura e lê, em modo só de leitura, a composição corporal, o movimento, os treinos, as calorias, as proteínas e a água. Não escreve dados de volta.",
        "site.health.detail.body": "O acesso ao Apple Health é opcional e limitado às permissões que concede. O GLPzy importa o histórico de peso e a altura e lê, em modo só de leitura, a composição corporal, o movimento, os treinos, as calorias, as proteínas e a água. Não escreve dados de volta.",
        "services.copy.apple.health.access.is.optional.and.limited.to": "O acesso ao Apple Health é opcional e limitado às permissões que concede. O GLPzy importa o histórico de peso e a altura e lê, em modo só de leitura, a composição corporal, o movimento, os treinos, as calorias, as proteínas e a água. Não escreve dados de volta.",
        "site.card.control.body": "O GLPzy criará primeiro uma cópia de segurança local e, em seguida, substituirá os registos locais neste dispositivo.",
        "onboarding.welcome.boundary.body": "O GLPzy ajuda-o a manter um registo mais claro do que aconteceu. Não diagnostica, prescreve nem escolhe a sua dose.",
        "paywall.legal": "Preço, período de cobrança e quaisquer detalhes da oferta introdutória são apresentados na sua conta da App Store antes da compra. Faça a gestão ou cancele nas definições da App Store.",
        "site.card.photos.body": "Compare, guarde e partilhe as suas fotografias de progresso.",
        "site.card.medication.title": "Escolha o seu medicamento",
        "site.medications.title": "Escolha o seu medicamento",
        "site.product.related.title": "Escolha o seu medicamento",
        "site.product.related.body": "Todos os medicamentos e formas incluídos são apresentados aqui.",
        "site.data.detail.body": "O GLPzy cria primeiro uma cópia de segurança local e, em seguida, substitui os registos locais neste dispositivo.",
        "site.safety.detail.body": "O GLPzy ajuda-o a manter um registo mais claro do que aconteceu. Não diagnostica, prescreve nem escolhe a sua dose.",
        "site.terms.detail.body": "Preço, período de cobrança e quaisquer detalhes da oferta introdutória são apresentados na sua conta da App Store antes da compra. Faça a gestão ou cancele nas definições da App Store.",
    },
    "sk": {
        "site.card.provider.title": "Súhrn pre lekára",
        "site.product.card.summary.title": "Súhrn pre lekára",
        "site.card.provider.body": "Vytvorte jasný PDF súhrn na návštevu z vašej zaznamenanej liečby, hmotnosti, príznakov a meraní.",
        "site.product.card.summary.body": "Vytvorte jasný PDF súhrn na návštevu z vašej zaznamenanej liečby, hmotnosti, príznakov a meraní.",
        "site.card.log.body": "Majte dávku, hmotnosť, príznaky, chuť do jedla a fotografie spolu na jednom mieste.",
        "site.product.card.log.body": "Majte dávku, hmotnosť, príznaky, chuť do jedla a fotografie spolu na jednom mieste.",
    },
    "zh-hans": {
        "site.card.health.body": "Apple Health 访问权限是可选的，并且仅限于你授予的权限。GLPzy 会导入体重历史和身高，并以只读模式读取身体成分、活动、锻炼、卡路里、蛋白质和水的摘要。不会写回任何数据。",
    },
    "zh-hant": {
        "site.card.health.body": "Apple Health 存取權限是可選的，並且僅限於你授予的權限。GLPzy 會匯入體重歷史與身高，並以唯讀模式讀取身體組成、活動、訓練、卡路里、蛋白質與水的摘要。不會寫回任何資料。",
    },
}

LOCALE_REPLACEMENTS = {
    "ar": {"See App Store pricing": "عرض السعر في App Store"},
    "cs": {"See App Store pricing": "Zobrazit cenu v App Store"},
    "da": {"See App Store pricing": "Se pris i App Store"},
    "de": {"See App Store pricing": "Preis im App Store ansehen"},
    "et": {"See App Store pricing": "Vaata hinda App Store’is"},
    "fi": {"See App Store pricing": "Katso hinta App Storessa"},
    "es-es": {"See App Store pricing": "Ver precio en App Store"},
    "es-mx": {"See App Store pricing": "Ver precio en App Store"},
    "fr": {"See App Store pricing": "Voir le prix sur l’App Store"},
    "fr-ca": {"See App Store pricing": "Voir le prix sur l’App Store"},
    "id": {"See App Store pricing": "Lihat harga di App Store"},
    "it": {"See App Store pricing": "Vedi prezzo su App Store"},
    "ja": {"See App Store pricing": "App Storeで価格を見る"},
    "ko": {"See App Store pricing": "App Store 가격 보기"},
    "lv": {"See App Store pricing": "Skatīt cenu App Store"},
    "nb": {"See App Store pricing": "Se pris i App Store"},
    "nl": {
        "See App Store pricing": "Bekijk prijs in de App Store",
        "Steun": "Ondersteuning",
    },
    "pl": {"See App Store pricing": "Zobacz cenę w App Store"},
    "pt-br": {"See App Store pricing": "Ver preço na App Store"},
    "pt-pt": {
        "See App Store pricing": "Ver preço na App Store",
        "A a a a sua rotina GLP-1, organizada sem confusão": "A sua rotina GLP-1, organizada sem confusão",
        "Comece pela a a a sua rotina real.": "Comece com a sua rotina real.",
        "Escolha o o o seu medicamento": "Escolha o seu medicamento",
        "Compare, guarde e compartilhe as a as a as a as suas fotografias de progresso.": "Compare, guarde e partilhe as suas fotografias de progresso.",
        "Preço, período de cobrança e quaisquer detalhes da oferta introdutória são apresentados em a a a a a a sua conta App Store antes da compra.": "Preço, período de cobrança e quaisquer detalhes da oferta introdutória são apresentados na sua conta da App Store antes da compra.",
        "O O O GLPzy": "O GLPzy",
        "o o o seu medicamento": "o seu medicamento",
        "a a a a sua conta App Store": "na sua conta da App Store",
        "a a a a a a sua conta App Store": "na sua conta da App Store",
        "a as a as a as a as suas": "as suas",
        "No in-app account is required to record doses, weight, symptoms or reminders.": "Não é necessária uma conta na app para registar doses, peso, sintomas ou lembretes.",
        "Apple Health access is optional and limited to the permissions you grant. GLPzy imports body weight history and height, then reads body composition, movement, workout, calorie, protein and water summaries in read-only mode. Nothing is written back.": "O acesso ao Apple Health é opcional e limitado às permissões que concede. O GLPzy importa o histórico de peso e a altura e lê, em modo só de leitura, a composição corporal, o movimento, os treinos, as calorias, as proteínas e a água. Não escreve dados de volta.",
        "Create GLPzy Backup\u200b": "Criar cópia de segurança do GLPzy",
        "Compounded\u200b": "Medicação manipulada",
        "você usa": "utiliza",
        "você opte": "opte",
        "você pode": "pode",
        "Você pode": "Pode",
        "você concede": "concede",
        "GLPzy ajuda você": "O GLPzy ajuda-o",
        "escolhe sua dose": "escolhe a sua dose",
        "sua conta App Store": "a sua conta App Store",
        "sua próxima dose": "a próxima dose",
        "seu medicamento": "o seu medicamento",
        "seu rastreamento": "o seu acompanhamento",
        "Seus registos": "Os seus registos",
        "Registro": "Registo",
        "registro": "registo",
        "registros": "registos",
        "fotos": "fotografias",
        "suas fotografias": "as suas fotografias",
        "Contexto somente leitura de Apple Health": "Contexto só de leitura do Apple Health",
        "somente leitura": "só de leitura",
        "O acesso Apple Health é opcional": "O acesso ao Apple Health é opcional",
        "GLPzy importa histórico": "O GLPzy importa o histórico",
        "Contate o suporte": "Contacte o suporte",
        "Apoiar": "Suporte",
        "Revise o escopo do suporte, os contatos de privacidade e as orientações não emergenciais.": "Reveja o âmbito do suporte, os contactos de privacidade e as orientações não urgentes.",
        "Use o e-mail para questões técnicas, de privacidade, acessibilidade ou assinatura.": "Use o email para questões técnicas, de privacidade, acessibilidade ou subscrição.",
        "Escolha o formato que deseja compartilhar.": "Escolha o formato que pretende partilhar.",
        "compartilhar": "partilhar",
        "em uma solicitação de suporte": "num pedido de suporte",
        "GLPzy criará primeiro": "O GLPzy criará primeiro",
        "Configurações de App Store": "definições da App Store",
        "configurações de App Store": "definições da App Store",
        "Gerenciar assinatura": "Gerir subscrição",
        "Gerencie ou cancele": "Faça a gestão ou cancele",
        "são mostrados": "são apresentados",
        "Termos de uso": "Termos de utilização",
        "Para rastreamento pessoal": "Para acompanhamento pessoal",
        "rastreamento": "acompanhamento",
        "compromissos": "consultas",
        "salve": "guarde",
        "Widgets da tela inicial": "Widgets do ecrã principal",
        "contagem regressiva": "contagem decrescente",
        "em uma": "numa",
        "hero-via sual": "hero-visual",
        "hero-via a sual": "hero-visual",
        "hero-via a a sual": "hero-visual",
        "A a sua": "A sua",
        "a a sua": "a sua",
        "a as suas": "as suas",
        "na a sua conta": "na sua conta",
    },
    "ru": {"See App Store pricing": "Посмотреть цену в App Store"},
    "sk": {"See App Store pricing": "Pozrite si cenu v App Store"},
    "sv": {"See App Store pricing": "Se pris i App Store"},
    "th": {"See App Store pricing": "ดูราคาบน App Store"},
    "vi": {"See App Store pricing": "Xem giá trên App Store"},
    "zh-hans": {"See App Store pricing": "在 App Store 查看价格"},
    "zh-hant": {"See App Store pricing": "在 App Store 查看價格"},
}


def locale_for(path):
    relative = path.relative_to(ROOT)
    return relative.parts[0] if len(relative.parts) > 1 else "en"


def replace_i18n_text(text, replacements):
    updated = text
    for key, replacement in replacements.items():
        pattern = re.compile(r'(<[^>]+data-i18n="' + re.escape(key) + r'"[^>]*>)(.*?)(</[^>]+>)', re.S)
        updated = pattern.sub(lambda match: match.group(1) + replacement + match.group(3), updated)
    return updated


changed = []
for path in ROOT.rglob("*.html"):
    if ".git" in path.parts:
        continue
    text = path.read_text(encoding="utf-8")
    updated = text
    for before, after in REPLACEMENTS.items():
        updated = updated.replace(before, after)
    locale = locale_for(path)
    for before, after in LOCALE_REPLACEMENTS.get(locale, {}).items():
        updated = updated.replace(before, after)
    updated = replace_i18n_text(updated, DEFAULT_BLOCK_REPLACEMENTS)
    updated = replace_i18n_text(updated, LOCALE_BLOCK_REPLACEMENTS.get(locale, {}))
    if path.name == "index.html":
        updated = replace_i18n_text(updated, INDEX_BLOCK_REPLACEMENTS.get(locale, {}))
    if locale == "pt-pt":
        # Repair repeated article tokens introduced by the earlier bulk rewrite.
        updated = re.sub(r"\bA(?:\s+a)+\b", "A", updated)
        updated = re.sub(r"\ba(?:\s+a)+\b", "a", updated)
        updated = re.sub(r"\bO(?:\s+O)+\b", "O", updated)
        updated = re.sub(r"\bo(?:\s+o)+\b", "o", updated)
        updated = re.sub(r"\bas(?:\s+a)+\b", "as", updated)
        updated = updated.replace("hero-via sual", "hero-visual")
        updated = updated.replace("hero-via a sual", "hero-visual")
    if updated != text:
        path.write_text(updated, encoding="utf-8")
        changed.append(path.relative_to(ROOT).as_posix())

for item in changed:
    print(item)
print(f"Updated {len(changed)} HTML files.")
